# visit http://jekyllrb.com/docs/configuration/ for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md", "Gemfile", "Gemfile.lock"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: thinkbinaryblog
google_analytics:  UA-365801-4
title: ThinkBinary

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: dbyll

description: Stylish Jekyll Theme
author:
  name: Pervez Choudhury
  email: blog@thinkbinary.co.uk
  github: codedemonuk
  twitter: pervezc
  linkedin: pervezc
  bio: The personal blog of Pervez Choudhury. A software developer from Bushey, UK
  email_md5: a3e5a771b79eb30f64b72b42e349b8d9

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
permalink: /:year/:month/:day/:title

# set it as url of an image
# sidebar_background_image: /path/to/img.jpg

BASE_PATH:

gems:
  - jekyll-paginate

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Pervez Choudhury"
      comments: true