### GENERAL SETTINGS ###

# Site settings
title: ThinkBinary
description: "The personal web blog of Pervez Choudhury. A software developer from Bushey, UK."
analytics: UA-365801-4
baseurl: "" #important: start with /
url: "https://www.thinkbinary.co.uk"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: http://www.facebook.com/pervezc
  - title: twitter
    url: http://twitter.com/pervezc
  - title: linkedin
    url: https://uk.linkedin.com/in/pervezc
  - title: github
    url: https://github.com/codedemonuk
  - title: stack-overflow
    url: http://stackoverflow.com/users/41673/pervez-choudhury

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
email: blog@thinkbinary.co.uk

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "A .Net developer from Bushey, Hertfordshire.  Also serves as a Councillor for Hertsmere Borough Council and a Governor for Bushey Heath Primary School.  All views expressed are my own."

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Pervez Choudhury"
      comments: true
